disabled_rules:
  - line_length
  - todo
  - nesting
  - private_action
  - multiple_closures_with_trailing_closure
excluded:
  - API.swift
  - Pods
  - checkouts
  - SourcePackages
identifier_name:
  excluded:
    - at
    - cg
    - id
    - on
    - up
    - x
large_tuple:
  warning: 4
opt_in_rules:
  - anyobject_protocol
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_object_literal
  - duplicate_imports
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - inert_defer
  - joined_default_parameter
  - last_where
  - legacy_hashing
  - legacy_random
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - nimble_operator
  - no_fallthrough_only
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_set_access_control
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unused_control_flow_label
  - unused_import
  - unused_private_declaration
  - unused_setter_value
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition
trailing_whitespace:
  ignores_empty_lines: true

